# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-18 05:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='Article is published'),
        ),
    ]
