# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-18 06:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_article_is_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='article', verbose_name='Article image'),
        ),
    ]
